apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3000 # this is service port will be exposed 
      targetPort: 80 # this port is the port that POD are exposing to talk